2019-11-23 18:07:04,042	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 127.0.0.1, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 380, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 73, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 82, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 564, in resolve
    raise RuntimeError(msg % address_str)

2019-11-23 18:07:04,043	Job number is not available yet
2019-11-23 18:07:04,043	Job number is not available yet
2019-11-23 18:07:04,046	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_stat_w50VPT.log
2019-11-23 18:07:04,047	File not found to collect: validation_error.yaml
2019-11-23 18:07:04,047	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/answ_s8Qkcb.log
2019-11-23 18:07:04,047	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_kja488.log
2019-11-23 18:07:04,047	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phout_IWZRrz.log
2019-11-23 18:07:47,479	Exception occurred:
<type 'exceptions.OSError'>: [Errno 2] No such file or directory: 'get.ammo'
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 380, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 73, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 106, in config_file
    self._config_file = self.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 114, in compose_config
    streams_config += stream.compose_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 288, in compose_config
    self.stepper_wrapper.prepare_stepper()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 212, in prepare_stepper
    self.stpd = self.__get_stpd_filename()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 263, in __get_stpd_filename
    hashed_str += sep + opener.hash

  File "/usr/local/lib/python2.7/dist-packages/netort/resource.py", line 151, in hash
    stat = os.stat(self.f_path)

2019-11-23 18:07:47,480	Job number is not available yet
2019-11-23 18:07:47,480	Job number is not available yet
2019-11-23 18:07:47,483	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-47.413679/phout_KIwtFK.log
2019-11-23 18:07:47,484	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-47.413679/phantom__CesFT.log
2019-11-23 18:07:47,484	File not found to collect: validation_error.yaml
2019-11-23 18:07:47,484	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-47.413679/phantom_stat_YoqOtP.log
2019-11-23 18:07:47,484	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-47.413679/answ_Su8K1K.log
